### ISSUE TITLE
Error when using through DCTL OFX in Resolve 16

### ISSUE THREAD

**Issue by jamiecollinson** [hotgluebanjo/halation-dctl#1]
Firstly, great effect - I've been looking for a more physically accurate halation and this looks great!

I've tried applying the DCTL through the LUTs menu and this works great, nice subtle effect but not configurable. When I try to apply it via a DCTL OFX node nothing happens, and inspecting the Resolve logs I see this:

```
[0x7000049ba000] | DVIP                 | ERROR | 2022-11-15 09:05:27,056 | DaVinci CTL compilation failed.
[0x7000049ba000] | DVIP                 | ERROR | 2022-11-15 09:05:27,057 | Failed to build program.
Build Status: -2
Build Options: -w -DDEVICE_IS_OPENCL -DCOMPILER_IS_DVIP_RT -DUSE_HALFFLOAT -DVENDOR_IS_AMD -cl-mad-enable -cl-fast-relaxed-math
Build Log: <program source>:1419:171: error: expected ';' after top level declarator
__DEVICE__ float3 transform(int p_Width, int p_Height, int p_X, int p_Y, __TEXTURE__ p_TexR, __TEXTURE__ p_TexG, __TEXTURE__ p_TexB, __GLOBAL__ DCTLUIParams* p_UIParams )
                                                                                                                                                                          ^
                                                                                                                                                                          ;
<program source>:1420:12: error: global variables must have a constant address space qualifier
    float3 rgb = _sample(p_TexR, p_TexG, p_TexB, p_X, p_Y);
           ^
<program source>:1420:26: error: use of undeclared identifier 'p_TexR'
    float3 rgb = _sample(p_TexR, p_TexG, p_TexB, p_X, p_Y);
                         ^
<program source>:1422:5: error: expected identifier or '('
    if (SIZE < 1e-10) return rgb;
    ^
<program source>:1424:12: error: global variables must have a constant address space qualifier
    float3 blurred = exp_blur(p_TexR, p_TexG, p_TexB, p_X, p_Y, SIZE);
           ^
<program source>:1424:31: error: use of undeclared identifier 'p_TexR'
    float3 blurred = exp_blur(p_TexR, p_TexG, p_TexB, p_X, p_Y, SIZE);
                              ^
<program source>:1425:12: error: global variables must have a constant address space qualifier
    float3 result, color, halated;
           ^
<program source>:1425:20: error: global variables must have a constant address space qualifier
    float3 result, color, halated;
                   ^
<program source>:1425:27: error: global variables must have a constant address space qualifier
    float3 result, color, halated;
                          ^
<program source>:1427:5: error: expected identifier or '('
    switch (METHOD) {float SIZE = p_UIParams->sliderFloatParams[0];float COLOR = p_UIParams->sliderFloatParams[1];int METHOD = p_UIParams->comboBoxParams[0];
    ^
<program source>:1441:5: error: expected identifier or '('
    return result;
    ^
<program source>:1442:1: error: extraneous closing brace ('}')
}
^
```

I'm new to DCTL but am familiar with C, and this doesn't make much sense to me as (e.g.) your `rgb` variable in `transform` is not global.

I guess the issue might be that I'm running on an old version of Resolve Studio (16.2.2.011) as it's an old Mac, but is there anything I can do to try and fix? Happy to do some work but as I'm new to DCTL not sure what I should try so any pointers welcome.

In case it helps here is my compound node setup, justing converting to linear gamma and then back again via CSTs, with the halation node in the middle. As you can see the UI parameters are being parsed correctly:

![Screen Shot 2022-11-15 at 09 23 21](https://user-images.githubusercontent.com/3263722/201881580-444f03a6-4642-4d8a-aecf-78cb08bb7cbb.png)

**Comment by hotgluebanjo** [comment]
Sorry, I missed this. This is puzzling. I've never gotten errors quite like this, though I'm not on Mac.

Seems like it's incorrectly interpreting the body of the `transform` function: `error: extraneous closing brace ('}')` plus wanting a semicolon after. This is the first time I've seen the `transform` signature with a UI params pointer. It looks like it's inserting local variables using the global param list, but it's getting the scope wrong: `METHOD` is initialized inside the `switch` on `METHOD`, which it's parsing as the body.

> As you can see the UI parameters are being parsed correctly:

Interesting. For me, if the DCTL fails to compile, its parameters don't appear. That could be system-specific though.

Honestly I have no idea. Maybe try adding semicolons after each `DEFINE_UI_PARAMS()`. Update Resolve if you can. If you're in a pinch or still want to use it, you can just change the default values (first float value after `DCTLUI_SLIDER_FLOAT`) to what you want (or swap them out with `#define`s) and apply via the LUT menu. It's very odd that it works there but not in the OFX plugin. An update to the next minor Resolve 16 version might fix this. All the old builds are here: https://www.blackmagicdesign.com/support/family/davinci-resolve-and-fusion

**Comment by jamiecollinson** [comment]
Thanks for taking a look, and I'm reassured that you're a bit mystified too :-) Probably time for me to upgrade anyway, and I can work around.

Appreciate the suggestions and I'll try your suggested tweaks (and good idea to try next minor version - I think I can run any of the 16.x versions) once I'm back at my desk next week. I'll post results just in case it helps anyone else.

Thanks again for the work - really lovely effect and as a coder I'm enjoying learning more about DCTLs.

**Comment by hotgluebanjo** [comment]
@jamiecollinson did you get it working?

**Comment by jamiecollinson** [comment]
Sorry I never updated the issue!Adding semicolons didn’t work so I updated the default value - worked fine for my purposes and got a great result thanks.I’ve since updated resolve so guess this one remains a mystery and can be closed unless someone else with an old version of resolve digs it up.On 30 Sep 2023, at 06:16, hotgluebanjo ***@***.***> wrote:﻿
@jamiecollinson did you get it working?

**Comment by hotgluebanjo** [comment]
Perhaps was a bug with the sliders. Strange one! I'll close this for now.
