### ISSUE TITLE
Artifacts when using DCTL in Resolve 18.1.3

### ISSUE THREAD

**Issue by jaynedoeh** [hotgluebanjo/halation-dctl#2]
Hello,

we recently graded some shots in a Resolve 17.4.X project where this DCTL was used without any issue or complication. We did some tests upgrading to Resolve 18.1.3 as of this writing and noticed that somehow this DCTL now generates bright yellow pixel spots in a random manner. Do you know if Blackmagic did break anything regarding this DCTL?

Edit: this issue is both present on Linux and on Mac. Tried with tetra and trilin LUT interpolation settings and with ACES reference gamut compress and without.

**Comment by hotgluebanjo** [comment]
Hi. Sorry for the delay. I can't reproduce this with 18.1.3 on Windows. The inconsistency between platforms is frustrating. Did you manage to fix it? Perhaps give it a try with 18.1.4 if not.

**Comment by jaynedoeh** [comment]
Hey,

I deleted the issue since it happened only on one project and didnt produce
any issues on another one. Sorry about that.

All the Best
