### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by agriggio** [hotgluebanjo/halation-dctl#3]
Hi, I didn't find any information regarding the license of the code. I would like to borrow parts of it but I want to make sure that I can... could you clarify please?
Thanks!

**Comment by hotgluebanjo** [comment]
Ah, may I ask what you're making?

**Comment by agriggio** [comment]
I'd like to add a halation filter to ART: https://bitbucket.org/agriggio/art/wiki/Home

**Comment by hotgluebanjo** [comment]
Take whatever you need; that looks awesome!

Do check out the snail branch if you haven't. The kernel there is [proper exponential](https://www.desmos.com/calculator/awi9tq4zuu) and is still easy to approximate with SVD. Neither kernel is particularly good at emulating halation, but they'll look nice.

**Comment by agriggio** [comment]
Thanks! It's on master now FYI. And indeed the snail kernel looks nicer -- thanks for the tip!
